### PR TITLE
fix for issue #69

### PR DESCRIPTION
**Pull request by Adeeb-khan**
updated the migrateSubscriptions method

### CODE REVIEW

**Comment by chazemar** [comment]
I think we have to add an equals method into the Provider class. The method will check url/servicename/... attributes to compare objects.

**Comment by Adeeb-khan** [comment]
I think migrateSubscriptions method in SubscriptionManager class is for comparing  new configuration with the previous configuration.
Earlier url of provider was compared with new url of provider object in the migrateSubscriptions method.
Now i am comparing whole object with previously save object in the same method.

**Comment by chazemar** [comment]
I understand but how do you compare the whole object ? It seems that you used the default equals method of Object class.
https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)

**Comment by marcc-orange** [comment]
@Adeeb-khan overriding `equals` for a specific usage is less than ideal. `equals` and `hashcode` are used for many things in Java, mainly to prove uniqueness of an object in collections. So your modification might trigger some problems everywhere `Provider` are referenced in a `Set` or an `Hashtable`...

You want to check if two `Provider`s have the same `url`, `servicePath` and `serviceName`, this is not the equality between two `Provider` instances.

You should add a new method `hasSameOrigin(Provider otherProvider)` with an implementation looking like (it's missing null checks): 

```java
public boolean hasSameOrigin(Provider otherProvider) {
    return url.equals(otherProvider.url) && servicePath.equals(otherProvider.servicePath) && serviceName.equals(otherProvider.serviceName)
}
```

And then use this specific method in the `SubscriberManager` instead of `equals`.

**Comment by marcc-orange** [comment]
Supperseeded by #72

**Pull request closed without merging**
